[package]
name = "pgm_processor"
version = "0.1.0"
edition = "2024"

[lib]
name = "pgm_processor"
crate-type = ["cdylib"] 

[dependencies]
image = "0.25.8"
ndarray = "0.16.1"
numpy = "0.27.0"
pyo3 = { version = "0.27.1", features = ["extension-module"] }
rand = "0.9.2"
rand_distr = "0.5.1"
